### ISSUE TITLE
Similar projects

### ISSUE THREAD

**Issue by ltalirz** [tilde-lab/tilde#54]
Dear Evgeny,
via our contact with Pierre Villars, I came across this repository with your list of "similar projects".
I believe most of us working in this field have a hard time keeping up with developments as new projects are popping up on a weekly basis, and maintaining such a list seems very worthwhile to me.
However, it could be beneficial to spread this task over more shoulders and so I was wondering whether you would agree to separate this list out into its own repository, where one could then accept pull requests from others, keeping it up to date?

I'm happy to take care of this, if you don't prefer to do it yourself.

Best wishes,
Leopold

**Comment by blokhin** [comment]
Dear Leopold,

indeed, I've already planned to isolate such a list couple of months ago, but totally forgot. Thanks for raising that!

The list now lives here: https://github.com/tilde-lab/awesome-materials-informatics

Please, let me know if it is OK.

**Comment by ltalirz** [comment]
Great, thanks a lot!
I'll probably be making some pull requests over the next months, and I'll let our group know about the list, so that they can do the same.
